# -*- coding: utf-8 -*-
"""Rpg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOQ-SzclB7Cm2eCZl9J2yU6NC4khjOcx
"""

classes = [
    "Mago", "Guerreiro", "Ladino", "Arqueiro", "Cavaleiro", "Espadachim", "Druida", "Feiticeiro"
]

pericias = {

}

import os

def limpar_tela():
    os.system('cls' if os.name == 'nt' else 'clear')

def criar_personagem ():
  vigor_base = 0
  forca_base = 0
  agilidade_base = 0
  inteligencia_base = 0
  PV = 0
  M = 0
  nome = input('Digite o nome do seu personagem: ')
  limpar_tela()
  print(f"Bem Vindo {nome}!")

  while True:
    try:
      for idx, (nome) in enumerate(classes):
        print(f"{idx}-{nome}")
      i = input('Escolha classe do seu personagem (Digite um número): ')
      i = int(i)
      classe = classes[i]
      if classe in classes:
        print(f"{classe} Selecionado!")
        break
      else:
        print("Digite um número válido!")
        continue
    except ValueError:
      print("Digite um valor válido!")
      continue
    except IndexError:
      print("Digite um número dentro das opções!")
      continue
  input('Digite enter para continuar: ')
  points = 10
  limpar_tela()
  print(f"Agora antes de você Distribuir seus Pontos nos Atributos, irei explicar o Sistema de Pontos de Vida e Mana: ")
  print(f"Status de {classe}: ")
  if classe == "Mago":
    print(f"Pontos de Vida (PV): 3 * Vigor + Inteligência")
    print(f"Mana: 5 * Inteligência + Inteligência")

  elif classe == "Guerreiro":
    print(f"Pontos de Vida (PV): 5 * Vigor + Força")
    print(f"Mana: 3 * Inteligência + Força")

  elif classe == "Ladino":
    print(f"Pontos de Vida (PV): 4 * Agilidade + Vigor")
    print(f"Mana: 3 * Inteligência")

  elif classe == "Arqueiro":
    print(f"Pontos de Vida (PV): 4 * Vigor + Agilidade")
    print(f"Mana: 3 * Inteligência + Agilidade")

  elif classe == "Cavaleiro":
    print(f"Pontos de Vida (PV): 7 * Vigor")
    print(f"Mana: 2 * Inteligência + Vigor")

  elif classe == "Espadachim":
    print(f"Pontos de Vida (PV): 4 * Agilidade + Vigor")
    print(f"Mana: 2 * Inteligência + Agilidade")

  elif classe == "Druida":
    print(f"Pontos de Vida (PV): 3 * Vigor + Vigor")
    print(f"Mana: 4 * Inteligência + Vigor")

  elif classe == "Feiticeiro":
    print(f"Pontos de Vida (PV): 2 * Vigor + Inteligência")
    print(f"Mana: 5 * Inteligência + Força")
  input('Digite enter para continuar: ')
  limpar_tela()
  while True:
    try:
      if vigor_base > 0 :
        pass
      else:
        print(f"Agora vamos criar seus Status, Você possui agora {points} pontos para distribuir. \n")
        vigor_base = int(input(f"Vigor: 1 + "))
        if vigor_base > points :
          print("Você não tem pontos suficientes!")
          vigor_base = 0
          continue
        vigor = vigor_base + 1
        points = points - vigor_base
        if points == 0 :
          print("Você usou todos os seus pontos!")
          input('\nDigite enter para continuar: ')
          break
      limpar_tela()
      if forca_base > 0 :
        pass
      else:
        print(f"Agora vamos criar seus Status, Você possui agora {points} pontos para distribuir. \n")
        print(f"Vigor: 1 + {vigor_base} = {vigor}")
        forca_base = int(input(f"\nForça: 1 + "))
        if forca_base > points :
          print("Você não tem pontos suficientes!")
          forca_base = 0
          continue
        forca = forca_base + 1
        points = points - forca_base
        if points == 0 :
          print("Você usou todos os seus pontos!")
          input('\nDigite enter para continuar: ')
          break
      limpar_tela()
      if agilidade_base > 0 :
        pass
      else:
        print(f"Agora vamos criar seus Status, Você possui agora {points} pontos para distribuir. \n")
        print(f"Vigor: 1 + {vigor_base} = {vigor}")
        print(f"\nForça: 1 + {forca_base} = {forca}")
        agilidade_base = int(input(f"\nAgilidade: 1 + "))
        if agilidade_base > points :
          print("Você não tem pontos suficientes!")
          agilidade_base = 0
          continue
        agilidade = agilidade_base + 1
        points = points - agilidade_base
        if points == 0 :
          print("Você usou todos os seus pontos!")
          input('\nDigite enter para continuar: ')
          break
      limpar_tela()
      if inteligencia_base > 0 :
        pass
      else:
        print(f"Agora vamos criar seus Status, Você possui agora {points} pontos para distribuir. \n")
        print(f"Vigor: 1 + {vigor_base} = {vigor}")
        print(f"\nForça: 1 + {forca_base} = {forca}")
        print(f"\nAgilidade: 1 + {agilidade_base} = {agilidade}")
        inteligencia_base = int(input(f"\nInteligência: 1 + "))
        if inteligencia_base > points :
          print("Você não tem pontos suficientes!")
          inteligencia_base = 0
          continue
        inteligencia = inteligencia_base + 1
        points = points - inteligencia_base
      limpar_tela()
      print(f"Agora vamos criar seus Status, Você possui agora {points} pontos para distribuir. \n")
      print(f"Vigor: 1 + {vigor_base} = {vigor}")
      print(f"\nForça: 1 + {forca_base} = {forca}")
      print(f"\nAgilidade: 1 + {agilidade_base} = {agilidade}")
      print(f"\nInteligência: 1 + {inteligencia_base} = {inteligencia}")
      input('\nDigite enter para continuar: ')
      break
    except ValueError:
      print("Digite um número válido!")
      continue
  limpar_tela()
  if classe == "Mago":
    PV = vigor * 3 + inteligencia
    M = inteligencia * 5 + inteligencia

  elif classe == "Guerreiro":
    PV = vigor * 5 + forca
    M = inteligencia * 3 + forca

  elif classe == "Ladino":
    PV = vigor * 4 + agilidade
    M = inteligencia * 3

  elif classe == "Arqueiro":
    PV = vigor * 4 + agilidade
    M = inteligencia * 3 + agilidade

  elif classe == "Cavaleiro":
    PV = vigor * 7
    M = inteligencia * 2 + vigor

  elif classe == "Espadachim":
    PV = vigor * 4 + agilidade
    M = inteligencia * 2 + agilidade

  elif classe == "Druida":
    PV = vigor * 3 + vigor
    M = inteligencia * 4 + vigor

  else:
    PV = vigor * 2 + inteligencia
    M = inteligencia * 5 + forca
  print(f"Status criado com sucesso!\n")
  print("Atributos: ")
  print(f"Vigor: {vigor}")
  print(f"Força: {forca}")
  print(f"Agilidade: {agilidade}")
  print(f"Inteligência: {inteligencia}")
  print(f"Pontos Restantes: {points}")
  print(f"\nPontos de Vida(PV): {PV}")
  print(f"Mana: {M}")
  input('\nDigite enter para continuar: ')
  limpar_tela()
  return PV, M, vigor, forca, agilidade, inteligencia, classe, nome

def definir_pericia(vigor, forca, agilidade, inteligencia, classe):

PV, M, vigor, forca, agilidade, inteligencia, classe, nome = criar_personagem()
definir_pericia(vigor, forca, agilidade, inteligencia, classe)